### ISSUE TITLE
Punch View Page needs updates 

### ISSUE THREAD

**Issue by devin2712** [devin2712/timesheet#12]
- When a user is punched in, the total time column tries to calculate with an invalid "end date" and shows a not a number error.
- You have minute(s), but it's fairly easy to determine the need for plurality in the language.
- Do you have support for hours? That's a much more common unit of time for worked hours. It will need to be more than simply one-line of momentJS-based calculations in a jade file.
- No need to ask for a name of a CSV file (no service does this) — Just do a date-stamped export file name, e.g. 20151118-ExportedHours.csv.
- The Export to CSV button shouldn't generate a file on our root directory.  That doesn't make sense.  If anything, put it in a separate directory. But furthermore, this just reveals everyone's punch data and is a clear and obvious security flaw.
- Try implementing export to CSV so that it just triggers a download to the computer's browser! 
- DO NOT USE JAVASCRIPT ALERT to notify a user of a successful csv file creation. That is horrible UI design and we can do better. 
- If you do an immediate download, you might not even need to deal with a "your file was successfully created" notification.

**Comment by pmatla95** [comment]
Everything has been fixed, except the file for CSV export is still in the root directory. Using fs.unlinkSync(filename) seems to be the way to do so, however when implemented it timesout the page and draws an error.
