### ISSUE TITLE
Responsive tables

### ISSUE THREAD

**Issue by devin2712** [devin2712/timesheet#13]
Someone please take up this bug:

We need to begin using tables for the punch display (this would affect view/process views)

- they need to use tables
- they need to work well for mobile or have mobile support

**Comment by pmatla95** [comment]
I can help, are you asking for html like tables??

**Comment by devin2712** [comment]
@pmatla95 yea they should be refactored to use HTML tables 

refer to http://getskeleton.com/#tables
