### ISSUE TITLE
Should admin have access to punching?

### ISSUE THREAD

**Issue by devin2712** [devin2712/timesheet#14]
CC ALL : @pmatla95 @apelisson57 @yim95 

Should we allow the admin account to have its own punches?
Should we just disable it so the admin account can just "process" and view all the accounts?

Comment below and we can develop accordingly.

**Comment by apelisson57** [comment]
I think that if the admin is on the payroll like the employees are, the system should collect and process admin punches like it does for employee punches. That would depend on how PTL distinguishes managers and regular employees in regards to payroll/shifts (i. e. whether or not the manager clocks in and out of the store just like the employees do and is paid by the hour like the employees are).

@yim95 can you offer some insight on how PTL handles the manager's shifts, etc.

**Comment by devin2712** [comment]
@yim95 bump
